version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: ecom-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth"]
      interval: 30s
      timeout: 30s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecom-pgadmin
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5051:443"
      - "5050:80"
volumes:
  postgres:
